### ISSUE TITLE
'certificate has expired' when trying to connect to https://sparql.rhea-db.org/sparql endpoint

### ISSUE THREAD

**Issue by sergyr** [zazuko/vscode-sparql-notebook#13]
trying to configure endpoint connections in the SPARQL Notebook side panel.
Added endpoint https://sparql.rhea-db.org/sparql (no username or password)
When pressing 'Connect to Database' getting an error 'Failed to connect to "Rhea": certificate has expired'
I don't see anything wrong with the certificate.

**Comment by ktk** [comment]
Please see #2 how to fix it. We can't do much, seems to be a VS Code problem.

**Comment by sergyr** [comment]
Thanks. Adding
"http.systemCertificates": false,

to user settings.json helped.
