### ISSUE TITLE
Checklist MD not supported

### ISSUE THREAD

**Issue by kvistgaard** [zazuko/vscode-sparql-notebook#14]
`- [ ] ` should create
- [ ]
according to https://github.github.com/gfm/
but doesn't

**Comment by BenjaminHofstetter** [comment]
https://github.com/Microsoft/vscode/issues/53993

**Comment by BenjaminHofstetter** [comment]
this is a vs code issue https://github.com/microsoft/vscode/issues/53993
you can. find extensions for this functionality.
