### ISSUE TITLE
Failing query on notebook on Wikidata

### ISSUE THREAD

**Issue by lubianat** [zazuko/vscode-sparql-notebook#18]
Hello, 

I am trying to connect the extension to Wikidata, but currently it is failing for the Wikidata SPARQL endpoint. It connects with the query service URL (https://query.wikidata.org/), but, when I try some query, like 
```
SELECT 
  ?item ?gene
WHERE 
{
  BIND(wd:Q1072 as ?item)
  ?gene wdt:P5572 ?item .
  ?gene wdt:P703 wd:Q15978631 .
}
```

I get the following error: 

[Error - 10:20:56 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read properties of undefined (reading 'getText')
  Code: -32603 

I imagine there is something to do with https://github.com/zazuko/vscode-sparql-notebook/blob/b464625635a61ee43a542d7f13805cbaedb650c7/src/sparql-notebook-controller.ts#L36

The LINDAS endpoint is queried just fine, though. Any idea what might be happening? Thanks!

**Comment by ktk** [comment]
This is a bit confusing with SPARQL: What you use at Wikidata is the *frontend* for querying, also called the "SPARQL query service GUI". If you want to run the query on your own, you need to send it to the SPARQL *endpoint*, which is defined here at Wikidata: https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service

Try replacing the service URL with this one: `https://query.wikidata.org/bigdata/namespace/wdq/sparql`.

**Comment by lubianat** [comment]
Thanks @ktk , that worked! 

As a note, I first tried `https://query.wikidata.org/sparql`, listed in <https://www.mediawiki.org/wiki/Wikidata_Query_Service/User_Manual#SPARQL_endpoint> and it failed with a 404 error. 

I though it was the endpoint itself (I use it all the time), but it is [an alias](https://people.wikimedia.org/~bearloga/notes/wdqs-python.html) or something like this (not sure of the inner workings). 

When I tried setting up the frontend URL, even though it sound I could _connect_ but not query. 

Maybe other error messages could improve the user experience in that case?

Anyways, thanks again, awesome plugin

**Comment by ktk** [comment]
Hmm interesting, haven't seen `/sparql` so far. It works for me with curl, for example:

```sh
curl -G https://query.wikidata.org/sparql \
 --data-urlencode query='
select distinct ?type where {
?thing a ?type
}
limit 20
'
```

**Comment by BenjaminHofstetter** [comment]
@lubianat and just for your information. The error you saw is from the stardog sparql language server extension. Stardog is aware of it #16 

```
[Error - 10:20:56 PM] Request textDocument/hover failed.
Message: Request textDocument/hover failed with message: Cannot read properties of undefined (reading 'getText')
Code: -32603

```
