### ISSUE TITLE
Failed to connect to "dbpedia": certificate has expired

### ISSUE THREAD

**Issue by kvistgaard** [zazuko/vscode-sparql-notebook#2]
This 👆 is the message I get when trying to connect to DBpedia endpoint

![image](https://user-images.githubusercontent.com/7572721/157382578-9b8ed6dd-1b2b-4852-a577-451508010a16.png)

I tried with a couple of other endpoints, including Wikidata, no issues there.

**Comment by BenjaminHofstetter** [comment]
It works for me ...
<img width="1362" alt="Screenshot 2022-03-09 at 08 55 06" src="https://user-images.githubusercontent.com/8033981/157397720-59309961-6232-4878-ace0-3d77c0683a2f.png">

Can you check if something like this can help you? 
https://github.com/microsoft/vscode/issues/97434#issuecomment-812094349

**Comment by kvistgaard** [comment]
Thanks, I checked. This seems to be instruction for Mac. I guess the equivalent in Windows is Credential Manager but there I can't find expired certificates. I tried also [other suggestions](https://stackoverflow.com/questions/56140439/remove-expired-certificates-with-powershell).

**Comment by BenjaminHofstetter** [comment]
There is hope that it’s related to https://github.com/microsoft/vscode/issues/136787

**Comment by kvistgaard** [comment]
Thanks. That worked.
