### ISSUE TITLE
After connection to https://query.wikidata.org and run query result is not visible

### ISSUE THREAD

**Issue by koryfeusz** [zazuko/vscode-sparql-notebook#22]
Connection: `https://query.wikidata.org`

query:
```
SELECT ?child
WHERE
{
# ?child  father   Bach
  ?child wdt:P22 wd:Q1339
}
```
seems result should be visible but is not:

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/6771628/182136898-f6f9f895-0993-401c-b8b5-f5a6d4c79719.png">

**Comment by BenjaminHofstetter** [comment]
Maybe I don't get the problem. Your endpoint is `https://query.wikidata.org`?

This is returning an HTML file. If you execute this query with another Wikidata endpoint this query works.
(for endpoints without authentication you can include the endpoint with a comment like this [endpoint=https://query.wikidata.org/bigdata/namespace/wdq/sparql] )


```sparql
#
# Test [endpoint=https://query.wikidata.org/bigdata/namespace/wdq/sparql] Test 
# 
SELECT ?child
WHERE
{
# ?child  father   Bach
  ?child wdt:P22 wd:Q1339
} LIMIT 100
```
