### ISSUE TITLE
[wish] Configure different endpoint per cell

### ISSUE THREAD

**Issue by kvistgaard** [zazuko/vscode-sparql-notebook#3]

**Comment by BenjaminHofstetter** [comment]
This is indeed a good idea.

### Why do we need "Endpoint per cell"?

- In SPARQL Classes we want a notebook with Examples or Exercises to solve.
   - These Exercises are not all for the same endpoint
- SPARQL notebooks are not bound to an Endpoint
   - You have to choose the Endpoint (with Connections menu).
   -  It makes the notebook harder to share
   - You have to use a markdown Cell to say something about the endpoint 

### What is not good right now:

- A notebook has no information about a SPARQL Endpoint (Connection)
   - The Endpoint configuration is outside the notebook
- Most SPARQL Queries are only meaningful in combination with a Dataset (or SPARQL endpoint)
   - This is currently not visible in the notebook

These two issues are somehow the same just another point of view. 

### Technical problems

- There is no way to add information about a code cell. Maybe there is with cell metadata. I don't know if it's supported in the API. 
- We have to differentiate between Endpoints with Credentials and without Credentials
- How do we make that endpoint configuration option available for the user
- There are only two types of Cells. Markdown and SPARQL Code Cells. That is limiting us 


### Possible solution

We can provide a special configuration comment within a SPARQL query. Similar to Stardog query hints e.g. [#pragma group.joins](https://docs.stardog.com/operating-stardog/database-administration/managing-query-performance#groupjoins).

We have to distinguish two cases. The unauthenticated and the authenticated case. For unauthenticated cases we just need a query hint with the SPARQL endpoint URL e.g.  #sparql-notebook.endpoint=https://dbpedia.org/sparql

_Advantages_
- We don't need a connection configuration anymore.
- The endpoint is visible for the user.

_Disadvantages_
- This is not standard SPARQL
- This query hint is a speciality for this notebook 
- It's not working well with credentials 

 **How to use it with credentials?**
Currently passwords are stored within a connection "outside" the notebook.
To provide a way to have more than "one" connection within a notebook we can use a query hint to say what connection we have to use for this query. And reference the connection with it's name. e.g.  #sparql-notebook.connection='DB Pedia'

Then we have to maintain the connections separate to the endpoint. That is not nice. And there is a relation between the notebook connection names in notebook cells and configured connections. And all users have to use the same name. That is very inconvenient and we cannot assume all Users use the same name for the same connection. It has too many downsides to do it like this. 

We may ask for credentials to create temporal connection objects before executing the query. 


**We don't have to focus on the authenticated case**

At the moment we can focus on the simple case where we just need a SPARQL Endpoint. Let's see how it feels.

**Comment by BenjaminHofstetter** [comment]
For inspiration https://github.com/blazegraph/database/wiki/QueryHints

**Comment by kvistgaard** [comment]
What about this: for open endpoints to give the endpoint URL in the SPARQL query as a comment?

**Comment by BenjaminHofstetter** [comment]
@kvistgaard what do you think about that...

```sparql
#
# *endpoint https://query.wikidata.org/bigdata/namespace/wdq/sparql
#
PREFIX schema: <http://schema.org/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>


SELECT DISTINCT ?ms ?msLabel ?hos ?hosLabel 
 
WHERE {
  ?ms wdt:P463 wd:Q458;
      wdt:P35 ?hos .
      SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
```

**Comment by ktk** [comment]
But there is still a default one if it's not specified?

**Comment by BenjaminHofstetter** [comment]
in version 0.0.10

```sparql
# add the endpoint in a comment like this
# [endpoint=https://lindas.admin.ch/query]
#
SELECT....
```
