### ISSUE TITLE
Would it be theoretically possible to bundle a small SPARQL engine with the plugin?

### ISSUE THREAD

**Issue by matentzn** [zazuko/vscode-sparql-notebook#37]
It would be pretty awesome if it was somehow possible to do something like 

https://sparql.gtf.fyi

(SORRY submitted issue to fast)

It is most likely out of scope for the plugin, but is it maybe somehow possible to easily query a local ttl file without the need of having a SPARQL endpoint running? Happy for this issue to be immediately closed as out of scope, just checking.

**Comment by ktk** [comment]
We talked about this internally already, main problem is that VS Code is not a normal JavaScript environment. It's neither Node.js nor it is a browser. Which means getting things like that to work usually fails on some weird errors that can or cannot be solved easily.

If someone spends time on testing whatever we would need in VS Code we might work on it but without contributions or funding I don't think this will happen anytime soon.

**Comment by ktk** [comment]
@matentzn you might want to try this one as well https://github.com/elsevierlabs-os/linked-data

Didn't try it but it should be able to do SPARQL directly.

**Comment by matentzn** [comment]
Thank you @ktk!

**Comment by BenjaminHofstetter** [comment]
@matentzn are you still interested to have this feature ? I think i can implement it. 
In another project i have the need something similar for testing generated SPARQL queries. I can use the same functionality to implement this featue. 

Why do you need this feature? Just to know what is the scope of this feature.

**Comment by matentzn** [comment]
We are developing ontologies, so it's sometimes useful to quickly query a local file turtle or rdfxml file.

**Comment by kvistgaard** [comment]
I very often need to query local files. I've been doing this for years only with Topbraid composer.
I came just to add this wish to be able to run a query on a local file when I discovered this issue.
It will be very useful feature of SPARQL Notebook, and I thought it should be feasible because [this VSCode plugin](https://marketplace.visualstudio.com/items?itemName=Elsevier.linked-data) is able to do it.

**Comment by BenjaminHofstetter** [comment]
Thank you @kvistgaard. I am always happy to get feedback about features like this. The technical implementation is not very hard. It's more the "how to integrate it". But I am on it.

**Comment by VBP8501** [comment]
I would like to add my support to this feature. I've been using sparql notebooks since a while now and think querying a local file can help with education, data testing, development of ontologies, ... Many thanks!

**Comment by BenjaminHofstetter** [comment]
@VBP8501 @kvistgaard  @matentzn @ktk The feature is there. It's still a bit hidden, but you can use it. You can find the option in the context menu in the file explorer. The implementation uses Oxigraph, and I've tested it with 103,111 triples.

Please test it in 0.0.27 and give feedback.
![local-file-store](https://github.com/zazuko/vscode-sparql-notebook/assets/8033981/c02dc4bd-1cd1-4c01-8032-cc2d74fceb5c)

**Comment by VBP8501** [comment]
I just tested the functionality and it seems to work perfectly! Good job and thanks! :)

**Comment by matentzn** [comment]
Super, super cool! For my personal use cases, this gets me 85% of the way; to round it up to 100, would it be at all in the realms of possible to embed:

```
# [endpoint=file://my/dir/ontology.ttl]
```

So that I can have one sparqlbook which I link to X different sparql dumps which I can run all at once?

**Comment by BenjaminHofstetter** [comment]
@matentzn Thanks for sharing your feedback. I see your point. 

Now a bit unrelated to your need. I have a few questions. Having a local sparql endpoint is not just "run a query on a file". It provides more possibilities e.g. 

We can fill the local store with ...
- load many ttl files
- load it with a CONSTRUCT query performed to another store (you can call it create Views )
- load "federated" many CONSTRUCTs to different stores
- load a TTL file over http e.g. https://www.w3.org/2000/01/rdf-schema# 

and you can combine all together. 

or we can fill the local store with a CONSTRUCT run SHACL validation on it before we run our SELECT queries. 

Any opinion about things like this?

**Comment by BenjaminHofstetter** [comment]
now i see your workflow. Thank you @matentzn

**Comment by kvistgaard** [comment]
@BenjaminHofstetter , speaking of construct, I often need to save the resulting file. For example, currently, I have a CONSTRUCT query that works on a Wikibase instance, Wikibase doesn't provide the possibility to save as Turtle. There are ways to overcome that, but it would be way more convenient to view and save the result as Turtle, TriG, N-Quads, or JSON-LD.

**Comment by BenjaminHofstetter** [comment]
@matentzn in version 0.0.31 I added a Cell Status Bar showing the SPARQL Target and where it's coming from and the cell source (cell or a query file). You can hover over it to see the url or file path. 

In this version you can do this 

```sparql 
# [endpoint=./rdf/curia.nt]
```
the path can be absolute or relative. But I suggest to use relative path. to be portable. 

The File Endpoint is loading the triples during cell execution. This makes it a bit slow because it loads the file every time and this takes more time than executing the query :-)

**Comment by VBP8501** [comment]
I just found out that a plain RDF file doesn't seem to work as source. I've converted the file into turtle serialization and that worked fine.

Again... this local-file-as-source feature save so much time during my knowledge graph construction!

**Comment by VBP8501** [comment]
And next I found that when the file is refreshed and you relaunch a query, you'll get the same result. You need to redo the click-right-on-file and use-file-as-store

**Comment by kvistgaard** [comment]
@BenjaminHofstetter is there are a way to query several ttl files at once?

**Comment by MathiasVDA** [comment]
> @BenjaminHofstetter is there are a way to query several ttl files at once?

What I do now is use [ttl-merge](https://github.com/julianrojas87/ttl-merge) to merge several ttl files into one. 

It would be very cool if sparql-notebooks could use a similar method as [sparql-anything](https://github.com/SPARQL-Anything) to refer to local files or remote repo's, by using the SERVICE clause.

fyi, here is an example on how sparql-anything would query a local file:
```sparql
SELECT *
WHERE {
    SERVICE <x-sparql-anything:location=/data/BelgiumRailwayStations.csv,csv.headers=true> {
        ?s ?p ?o
    }
}
```

Now that I'm making a relation between sparql-notebook and sparql-anything... having a sparql-anything-notebook would be very very nice :)

**Comment by BenjaminHofstetter** [comment]
I personally use n-triple files. they can be easily concatenated. But I was thinking about providing the ability to combine multiple file. I am thinking about it how to implement it. 

SPARQL anything notebook sounds interesting.

**Comment by MathiasVDA** [comment]
Is the fx:location relative to the server or to the notebook?

**Comment by BenjaminHofstetter** [comment]
the location is relative to the server

**Comment by MathiasVDA** [comment]
Ok thanks. I know this is possible, my suggestion was more towards the notebook also having a sparql-anything server that can then help with local files like is meant in this issue. 

But this might be more advanced then what you would intend :)

**Comment by BenjaminHofstetter** [comment]
Yes currently the local file sparql endpoint is a WASM version of Oxigraph. For SPARQL anything would create a dependency to java. And currently I try to avoid that.
