### ISSUE TITLE
Define Proper HTTP Headers for Construct and Select SPARQL Requests

### ISSUE THREAD

**Issue by BenjaminHofstetter** [zazuko/vscode-sparql-notebook#56]
Some SPARQL endpoint (e.g. https://github.com/vemonet/rdflib-endpoint) can't handle combined Accept headers like "application/sparql-results+json,text/turtle" and will return their default (xml in this case) instead. the proposed refactoring uses only one type, depending of the type of query used.

proposed solution from @simonstey in PR #55

This is related to #28

**Comment by BenjaminHofstetter** [comment]
@simonste Thank you for your contribution! I appreciate your effort in addressing this issue. The proposed solution is too vague. I try to find another way.

**Comment by ktk** [comment]
I'm ok if we can find a proper workaround but in the end it's IMO a bug in whatever cannot handle combined accept headers. This is part of a standard and there are libraries taking care of that for almost any programming language out there. A quick google reveals for example https://pypi.org/project/accept-types/ for Python.

So IMO that should become an issue at rdflib-endpoint instead.

**Comment by BenjaminHofstetter** [comment]
Indeed. But now I know why Virtuoso was always returning sparql-result+json instead of Turtle for a construct query.

**Comment by BenjaminHofstetter** [comment]
@simonstey published in 0.0.24
