### ISSUE TITLE
Save as markdown

### ISSUE THREAD

**Issue by kvistgaard** [zazuko/vscode-sparql-notebook#6]
It would be very useful to be able to save a notebook as pure MD for sharing. 

The cell should be saved as ```sparql code blocks:
```sparql 

```

**Comment by kvistgaard** [comment]
Doesn't need to use the VSCode save as. A SPARQL notebook command "Export to Markdown" or something like that would be perfect. I'm currently creating an [open wiki](https://kvistgaard.github.io/sparql/), initially to support my SPARQL training courses but also to be used as a general reference, where all content is standard markdown with SPARQL code highlighting rendered by CodeMirror, and a few non-standard MD elements that bring the graph experience. So, that's one of many use cases, where reusing the content from a SPARQL notebook as MD will be useful.

**Comment by BenjaminHofstetter** [comment]
Idea: default markdown serialization

**Comment by kvistgaard** [comment]
That would be great. Then with tools such as Foam (VSCode), Dendron(VSCode), Logseq and Obsidian, the SPARQL notebooks can be interlinked in between and with other MD files.

**Comment by BenjaminHofstetter** [comment]
added markdown export
