### ISSUE TITLE
Queries with COUNT not working in 0.0.31

### ISSUE THREAD

**Issue by kvistgaard** [zazuko/vscode-sparql-notebook#65]
I have tried a few different queries on several endpoints. They used to work with previous versions of SPARQL Notebook, but not anymore. It might not be related to counting because some other queries stopped giving bindings for numerical values.

**Comment by BenjaminHofstetter** [comment]
@kvistgaard do you have a sample query?

**Comment by kvistgaard** [comment]
Sure.
Here a [DBpedia query](https://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&qtxt=SELECT%20(COUNT%20(%3Fwork_of_Agatha_Christie)%20AS%20%3FNumber_of_AC_works)%0A%0A%7B%3Fwork_of_Agatha_Christie%20dbo%3Aauthor%20dbr%3AAgatha_Christie%20%7D%20%0A&format=text%2Fhtml&timeout=30000&signal_void=on&signal_unconnected=on), that returns 117, 
and the same gives no result in SPARQL Notebook
![image](https://github.com/zazuko/vscode-sparql-notebook/assets/7572721/23d4d6f4-a1ac-4014-b14f-e162242b41ba)

**Comment by BenjaminHofstetter** [comment]
@kvistgaard fixed it's in the marketplace

**Comment by kvistgaard** [comment]
Great. All fine now.
