### ISSUE TITLE
Copy query link 

### ISSUE THREAD

**Issue by kvistgaard** [zazuko/vscode-sparql-notebook#7]
It would be very useful as it is with other SPARQL editors, to be able to easily get the HTTP trace of the query. 

And maybe, in order not to clutter the current clean UI, it should be under more actions (...) and via key binding, but not as a separate icon.

**Comment by BenjaminHofstetter** [comment]
Do you have an example of this?

**Comment by kvistgaard** [comment]
If we have this query
```sparql
SELECT * {?book a dbo:Book} LIMIT 10
```
on DBpedia, with results format HTML table, such functionality should add two links in the ... menu
[Copy query link](https://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&qtxt=SELECT%20*%20%7B%3Fbook%20a%20dbo%3ABook%7D%20LIMIT%2010&format=text%2Fhtml&timeout=30000&signal_void=on&signal_unconnected=on)
[Copy query results link](https://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&query=SELECT+*+%7B%3Fbook+a+dbo%3ABook%7D+LIMIT+10&format=text%2Fhtml&timeout=30000&signal_void=on&signal_unconnected=on#)

Unkile the above links, selecting should not open the link but copy it to the clipboard.

**Comment by BenjaminHofstetter** [comment]
This works for Wikidata etc. But not for other stores
