### ISSUE TITLE
Using FROM clause yields 'Unknown query type'

### ISSUE THREAD

**Issue by mchlrch** [zazuko/vscode-sparql-notebook#74]
If the RDF dataset is specified using either of the `FROM` or `FROM NAMED` clauses, then "SPARQL error: Unknown query type" is shown.

Example query:
```
PREFIX cube: <https://cube.link/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

from <https://lindas.admin.ch/foen/cube>
select *
WHERE  
{ 
    BIND(<https://environment.ld.admin.ch/foen/ubd000502/1> AS ?cube)
    ?cube  rdf:type  cube:Cube
}
```

![image](https://github.com/zazuko/vscode-sparql-notebook/assets/877232/823eb57b-18f9-4e39-946a-eb2ddc0c1e64)

**Comment by BenjaminHofstetter** [comment]
fixed
