### ISSUE TITLE
Collapse prefixes

### ISSUE THREAD

**Issue by kvistgaard** [zazuko/vscode-sparql-notebook#8]
Like it is e.g. at https://yasgui.triply.cc

**Comment by BenjaminHofstetter** [comment]
Just discovered that one https://marketplace.visualstudio.com/items?itemName=Fireblossom.sparql-auto-completion

Install that extension and you have your desired prefix support

**Comment by kvistgaard** [comment]
I have all Stardog plugins and prefix collapse works for .rq and .sparql files but not for .sparqlbook files. Installed the suggested extension. No change.

**Comment by BenjaminHofstetter** [comment]
This is clearly desirable but it's out of scope for the notebook and should be done with a SPARQL LSP.
