### ISSUE TITLE
Does not accept file with REGEX pattern

### ISSUE THREAD

**Issue by kvistgaard** [zazuko/vscode-sparql-notebook#81]
When trying to set a SHACL shapes file to query, it gives an error

![image](https://github.com/zazuko/vscode-sparql-notebook/assets/7572721/c8de8b68-bd45-46f4-8580-1b13f2ff852e)

It is part of a regex pattern

```turtle
    sh:or (
        [ sh:datatype xsd:date ]
        [ sh:datatype xsd:string ; sh:pattern "^\d{2}/\d{2}/\d{4}$|^\d{4}/\d{2}/\d{2}$" ]
    ) ;
```

**Comment by BenjaminHofstetter** [comment]
@kvistgaard 
my editor is complains about your string too.
```ttl
sh:pattern "^\d{2}/\d{2}/\d{4}$|^\d{4}/\d{2}/\d{2}$" 
```
you have to escape with \\
e.g. 

```ttl
		sh:pattern "^\\d{3}-\\d{2}-\\d{4}$" ;
```

is it the problem ?

**Comment by kvistgaard** [comment]
Yes, indeed, the backlash itself needs escaping in the expression"". Thanks.
