### ISSUE TITLE
multiple endpoints in single cell

### ISSUE THREAD

**Issue by KonstantinKlepikov** [zazuko/vscode-sparql-notebook#84]
now (for this example cell) use only first sentence

```sql
# [endpoint=this.ttl]
# [endpoint=exthat.ttl]

SELECT ...
```

is possible use multiple sources?

**Comment by BenjaminHofstetter** [comment]
@KonstantinKlepikov no it's not possible. do you need this ?

**Comment by KonstantinKlepikov** [comment]
Yes. For research with small local data.

**Comment by BenjaminHofstetter** [comment]
Ok. I will investigate and include it what I have time to work on it.

**Comment by BenjaminHofstetter** [comment]
Basically I have this problem too.

I often have a folder with several TTL files. It should be possible not just to include multiple files. It should be possible ass a folder or 'output/*.ttl' 

There are two different ways to use RDF files.
1. define it like and endpoint in SAPRQL comment 
2. use right click on a file and Choose "Use file as Store" or something like that



Test:
- Test it on windows too.

**Comment by BenjaminHofstetter** [comment]
@KonstantinKlepikov 

in version 0.0.39 you can use multiple entires or patterns 

```sparql
# [endpoint=./rdf/curia.nt]
```

or 
```sparql
# [endpoint=./rdf/*]
```
or 

```sparql
# [endpoint=rdf/*]
```

or 


```sparql
# [endpoint=./rdf/{a,b}.ttl]
```

or 

```sparql
# [endpoint=rdf/a.ttl]
# [endpoint=./rdf/b.ttl]
```

**Comment by BenjaminHofstetter** [comment]
it is there in version. the current version ins now 1.0.0 
https://marketplace.visualstudio.com/items?itemName=Zazuko.sparql-notebook

**Comment by KonstantinKlepikov** [comment]
@BenjaminHofstetter great job!
