### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by kvistgaard** [zazuko/vscode-sparql-notebook#9]
That's a big thing, I know, but I'm hoping some existing code, such as from the SPARQL Executor VSCode plugin, can be reused.

**Comment by BenjaminHofstetter** [comment]
What Errors do you mean? Like SPARQL language errors or query execution errors?

**Comment by kvistgaard** [comment]
Both and in that order of priority.

**Comment by BenjaminHofstetter** [comment]
Just saw that sparql executor  IS NO LONGER ACTIVELY MAINTAINED

**Comment by BenjaminHofstetter** [comment]
There are a lot of ideas around at Zazuko how to support the writing of SPARQL queries. Basically most of them should not be part of the Notebook it self. More like a SPARQL LSP. 

The same applies to EXPLAIN or PROFILE features.
